-- Lightning Migration 001: Add Missing Data Fields to Testimonies
-- Run in Supabase SQL Editor (safe — adds columns only, no data loss)
-- Generated by Jarvis — 2026-03-16

-- 1. Voice transcript (raw text from voice recording)
ALTER TABLE testimonies
  ADD COLUMN IF NOT EXISTS voice_transcript TEXT;

-- 2. Church linkage
ALTER TABLE testimonies
  ADD COLUMN IF NOT EXISTS church_id UUID REFERENCES groups(id) ON DELETE SET NULL;

-- 3. Track which version of intake questions was used
ALTER TABLE testimonies
  ADD COLUMN IF NOT EXISTS intake_question_version INTEGER DEFAULT 1;

-- 4. Testimony lifecycle status
ALTER TABLE testimonies
  ADD COLUMN IF NOT EXISTS testimony_status TEXT DEFAULT 'published'
  CHECK (testimony_status IN ('draft', 'published', 'deleted', 'flagged'));

-- 5. Track which AI model generated the testimony
ALTER TABLE testimonies
  ADD COLUMN IF NOT EXISTS ai_model_used TEXT DEFAULT 'claude-sonnet';

-- Indexes for new fields
CREATE INDEX IF NOT EXISTS testimonies_church_id_idx ON testimonies(church_id);
CREATE INDEX IF NOT EXISTS testimonies_status_idx ON testimonies(testimony_status);

-- Update existing records to have default status
UPDATE testimonies SET testimony_status = 'published' WHERE testimony_status IS NULL;
UPDATE testimonies SET intake_question_version = 1 WHERE intake_question_version IS NULL;
UPDATE testimonies SET ai_model_used = 'claude-sonnet' WHERE ai_model_used IS NULL;

-- Verify
SELECT
  column_name,
  data_type,
  column_default
FROM information_schema.columns
WHERE table_name = 'testimonies'
ORDER BY ordinal_position;
